name: K8S Risk Analysis
on: [push]
jobs:
  Risk-Analysis:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready."
      - name: Installing Kubescape Framework
        run: |
          make
      - name: Scanning kubernetes manifest files
        run: |
          kubescape scan '${{ github.workspace }}/templates/*.yml'